
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# Logging baseline
logging.level.root=ERROR
logging.level.com.dekraChallenge.dekra_challenge=ERROR
logging.level.org.springframework.security=ERROR

